spring:
  profiles:
    active: develop
  application:
    name: sample


#dev 환경
---
# Spring Boot configuration
spring:
  profiles: develop
  
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
    
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin
  main:
    allow-bean-definition-overriding: true

# Server configuration
server:
  port: 9100
  ssl:
    enabled: false
  error:
    whitelabel:
      enabled: true
  #http2:
  #  enabled: true
  max-http-header-size: 10240000
  servlet:
    session:
      timeout: 360m
      
# Logger configuration
logging:
  file: ../applog/sample/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    org.springframework: info
#    org.hibernate: info

#로그레벨의 순서는 아래와 같습니다.
#TRACE > DEBUG > INFO > WARN > ERROR
#- TRACE : 추적 레벨은 Debug보다 좀더 상세한 정보를 나타냅니다.
#- DEBUG : 프로그램을 디버깅하기 위한 정보를 표시합니다. (운영서버에서는 표시하지 않도록 설정함)
#- INFO  : 상태변경과 같은 정보성 로그를 표시합니다.
#- WARN  : 처리 가능한 문제, 향후 시스템 에러의 원인이 될 수 있는 경고성 메시지를 나타냄 
#- ERROR : 요청을 처리하는 중 오류가 발생한 경우 표시합니다.

# file
file:
  root-folder: ../appdata

